#!/usr/bin/env bash
#Bash script that configures an Ubuntu server with the below requirements

cp ~/etc/hosts ~/hosts.new

echo "127.0.0.2	localhost"
echo "8.8.8.8	facebook.com"

cp -f ~/hosts.new ~/etc/hosts
